all:
  hosts:
    node1:
      ansible_host: 192.168.10.110
      ip: 192.168.10.110
      access_ip: 192.168.10.110
    node2:
      ansible_host: 192.168.10.111
      ip: 192.168.10.111
      access_ip: 192.168.10.111
    node3:
      ansible_host: 192.168.10.112
      ip: 192.168.10.112
      access_ip: 192.168.10.112
    node4:
      ansible_host: 192.168.10.113
      ip: 192.168.10.113
      access_ip: 192.168.10.113
    node5:
      ansible_host: 192.168.10.114
      ip: 192.168.10.114
      access_ip: 192.168.10.114
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
